---
title: "Hydro data cleaning"
author: "Biz Yoder"
date: "2023-04-04"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

```{r}
#Import libraries
library(readxl) #import excel
library(dplyr) #pipes
library(forecast) #time series 
library(reshape2) #reshaping data
library(lubridate) #to deal with dates
library(tidyverse) #data wrangling
library(ggplot2) #for plotting
library(outliers) #to detect and deal with outliers
library(zoo)
library(margins) #for regression analysis
library(describedata) #for visualizing variable transformations
library(gtools)
library(robustHD) #for data cleaning
library(sjPlot) #for tables
library(sjmisc)
library(sjlabelled)
```

```{r}
#Import load data
multiplesheets <- function(fname) {
  ##get all sheet names
  sheets <- readxl::excel_sheets(fname)
  ##read in each sheet
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  ##convert data to df
  data_frame <- lapply(tibble, as.data.frame)
  ##name df
  names(data_frame) <- sheets
  ##return df
  print(data_frame)
}
  
path <- "./Data/EGENCO Daily Generation Data.xlsx"
all_hydro <- multiplesheets(path)
```

```{r}
#Combine all daily dfs for each year into one df
daily_data <- bind_rows(all_hydro[1:7])

#Check first and last dates in df
print(paste('The first date is in the combined daily dataframe is', head(daily_data$Date,1)))

print(paste('and the last date is', tail(daily_data$Date,1)))

daily_data = daily_data[complete.cases(daily_data[ , 2:6]),] 

daily_data$Date <- ymd(daily_data$Date)

#Add column for total amount generated
daily_data$total <- rowSums(daily_data[,2:6], na.rm = TRUE)

#Check for outliers
pvalue <- 0
daily_clean <- daily_data$total
nout <- 0
while(pvalue < 0.05){
  out_test <- grubbs.test(daily_clean, type=10)
  pvalue <- out_test$p.value
  
  if(pvalue < 0.05){
    daily_clean <- rm.outlier(daily_clean,fill=TRUE)
    nout <- nout+1
  }
}
cat("Number of outliers removed: ",nout,"\n")

daily_data$total <- daily_clean
boxplot(daily_data$total)$out

#Add column for month to create monthly averages
daily_data$month <- months(daily_data$Date)
daily_data$year <- format(daily_data$Date, format="%Y")

#Create dataframe with monthly average generation
monthly_data <- daily_data %>%
  filter(!is.na(total)) %>%
  group_by(year(Date), month(Date)) %>%
  summarise(monthly_generation = mean(total))

names(monthly_data) <- c("year", "month", "generation")

monthly_data$date <- make_date(year=monthly_data$year, month = monthly_data$month)

monthly_data <- cbind.data.frame(monthly_data$date, monthly_data$generation)
names(monthly_data) <- c("Date", "Total generation")

```

```{r}
#Import nighttime lights data
lights <- read.csv("./Data/nighttime_lights.csv")
```

```{r}
#Format nighttime lights data
##Subset df to only include radiance columns and district name
rad_data <- select(lights,contains("20")) #all radiance columns are named with date
rad_data$NAME_1 <- lights$NAME_1 #add district name column

##Format df from wide to long
rad_long <- melt(rad_data, na.rm = FALSE, value.name = 'radiance', id = 'NAME_1')

##Reformat date column to datetime object
rad_long$date <- rad_long$variable %>%
  gsub("X", "", .) %>% #remove the X infront of the date
  gsub("(\\d{4})(\\d{2})(\\d{2})$","\\1-\\2-\\3",.) #add -'s to the date

##Convert date column to datetime
rad_long$Date <- as.POSIXct(rad_long$date)

##Create one clean data frame of nighttime lights

nightlights <- cbind.data.frame(rad_long$Date, rad_long$NAME_1, rad_long$radiance)
names(nightlights) <- c("Date", "District", "Radiation")

##reshape back to wide format

nightlights_bydistrict <- reshape(nightlights, idvar="Date", timevar = "District", direction = "wide")
```

```{r}
##Import csv with plant capacity factors

capacity <- read.csv("./Data/capacity.csv")
capacity$date <- make_date(year = capacity$year, month = capacity$month)
capacity$total <- rowSums(capacity[,3:6], na.rm = TRUE)
capacity <- capacity[1:78,]

#capacity factor = total generation/(capacity*time)
monthly_data_cf <- monthly_data[5:82,]
capacity$cf_total <- ((monthly_data_cf$`Total generation`)/1000)/((capacity$total)*24)

```

```{r}
analysis_data <- cbind.data.frame(capacity$date, capacity$cf_total, monthly_data_cf$`Total generation`)

nightlights_foranalysis <- nightlights_bydistrict[2:74,]
analysis_data <- analysis_data[1:73,]
analysis_data <- cbind.data.frame(analysis_data, nightlights_foranalysis[,2:29])
analysis_data$totalradiation <- rowSums(analysis_data[,4:31], na.rm = TRUE)


#Check for outliers
pvalue <- 0
radiance_clean <- analysis_data$totalradiation
nout <- 0
while(pvalue < 0.05){
  out_test <- grubbs.test(radiance_clean, type=10)
  pvalue <- out_test$p.value
  
  if(pvalue < 0.05){
    radiance_clean <- rm.outlier(radiance_clean,fill=TRUE)
    nout <- nout+1
  }
}
cat("Number of outliers removed: ",nout,"\n")

analysis_data$totalradiation <- radiance_clean

names(analysis_data) <- c("Date", "Capacity_factor", "Total_generation", "Nsanje", "Mulanje", "Thyolo", "Chikwawa", "Blantyre", "Chiradzulu", "Zomba", "Neno", "Mwanza", "Balaka", "Ntcheu", "Machinga", "Phalombe", "Mangochi", "Dedza", "Salima", "Nkhotakota", "Likoma", "Nkhata_Bay", "Rumphi", "Karonga", "Chitipa", "Mzimba", "Mchinji", "Kasungu", "Ntchisi", "Dowa", "Lilongwe", "Total_radiance")

analysis_data$Total_generation <- winsorize(analysis_data$Total_generation, probs=c(0.05, 0.95), na.rm=FALSE, type=5)
analysis_data$Total_radiance <- winsorize(analysis_data$Total_radiance, probs=c(0.05, 0.95), na.rm=FALSE, type=4)

#Visualize potential transformations of variables
gladder(analysis_data$Total_radiance) # should log transform
analysis_data$ln_radiance <- log(analysis_data$Total_radiance)
gladder(analysis_data$Total_generation)
gladder(analysis_data$Capacity_factor)

#Plot capacity factor & ln(total radiance)
ggplot(data=analysis_data)+
  geom_point(aes(x=Capacity_factor, y=ln_radiance), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Capacity_factor, y=ln_radiance), method = "lm", formula = y ~ x, size = 1)+
  xlab("Monthly capacity factor")+
  ylab("Monthly NTL radiance \n in urban areas")

#Plot total generation & ln(total radiance)
ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_radiance), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_radiance), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in urban areas")

#Create district level total radiance
analysis_data$northern_radiance <- analysis_data$Chitipa + analysis_data$Karonga + analysis_data$Likoma + analysis_data$Mzimba + analysis_data$Nkhata_Bay + analysis_data$Rumphi

analysis_data$central_radiance <- analysis_data$Dedza + analysis_data$Dowa + analysis_data$Kasungu + analysis_data$Lilongwe + analysis_data$Mchinji + analysis_data$Nkhotakota + analysis_data$Ntcheu + analysis_data$Ntchisi + analysis_data$Salima

analysis_data$southern_radiance <- analysis_data$Balaka + analysis_data$Blantyre + analysis_data$Chikwawa + analysis_data$Chikwawa + analysis_data$Chiradzulu + analysis_data$Machinga + analysis_data$Mangochi + analysis_data$Mulanje + analysis_data$Mwanza + analysis_data$Nsanje + analysis_data$Thyolo + analysis_data$Zomba + analysis_data$Neno

analysis_data$northern_radiance <- winsorize(analysis_data$northern_radiance, probs=c(0.05, 0.95), na.rm=FALSE, type=5)
analysis_data$southern_radiance <- winsorize(analysis_data$southern_radiance, probs=c(0.05, 0.95), na.rm=FALSE, type=4)
analysis_data$central_radiance <- winsorize(analysis_data$central_radiance, probs=c(0.05, 0.95), na.rm=FALSE, type=4)

analysis_data$ln_northern <- log(analysis_data$northern_radiance)
analysis_data$ln_southern <- log(analysis_data$southern_radiance)
analysis_data$ln_central <- log(analysis_data$central_radiance)

#Plot total generation & regional radiance
ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_northern), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_northern), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in northern region")

ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_southern), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_southern), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in southern region")

ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_central), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_central), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in central region")

# by major cities
analysis_data$Lilongwe <- winsorize(analysis_data$Lilongwe, probs=c(0.05, 0.95), na.rm=FALSE, type=5)
analysis_data$Blantyre <- winsorize(analysis_data$Blantyre, probs=c(0.05, 0.95), na.rm=FALSE, type=4)
analysis_data$Mwanza <- winsorize(analysis_data$Mwanza, probs=c(0.05, 0.95), na.rm=FALSE, type=4)

analysis_data$ln_lilongwe <- log(analysis_data$Lilongwe)
analysis_data$ln_blantyre <- log(analysis_data$Blantyre)
analysis_data$ln_mwanza <- log(analysis_data$Mwanza)
analysis_data$ln_mwanza[is.na(analysis_data$ln_mwanza) | analysis_data$ln_mwanza=="-Inf"] = NA

#Plot total generation & major city radiance
ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_lilongwe), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_lilongwe), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in Lilongwe")

ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_blantyre), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_blantyre), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in Blantyre")

ggplot(data=analysis_data)+
  geom_point(aes(x=Total_generation, y=ln_mwanza), size=1.5, alpha=0.5)+
  geom_abline(intercept = 0)+
  stat_smooth(aes(x=Total_generation, y=ln_mwanza), method = "lm", formula = y ~ x, size = 1)+
  xlab("Total generation, monthly average")+
  ylab("Monthly NTL radiance \n in Mwanza")


radiance_byregion <- "ln_radiance ~  ln_northern + ln_southern + ln_central"
ols_region <- lm(radiance_byregion, data=analysis_data)
summary(ols_region, robust=TRUE)
summary(margins(ols_region))
plot(margins(ols_region))

radiance_cities <- "ln_radiance ~  ln_lilongwe + ln_blantyre + ln_mwanza "
ols_cities <- lm(radiance_cities, data=analysis_data)
summary(ols_cities, robust=TRUE)
summary(margins(ols_cities))
plot(margins(ols_cities))

```




```{r}
##Visualize hydro generation over time -- convert to time series

ts_hydro_monthly <- ts(analysis_data[,3], frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_cf_monthly <- ts(analysis_data[,2], frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_radiance_monthly <- ts(analysis_data$Total_radiance, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_lnradiance <- ts(analysis_data$ln_radiance, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_ln_central <- ts(analysis_data$ln_central, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_ln_southern <- ts(analysis_data$ln_southern, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_ln_northern <- ts(analysis_data$ln_northern, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_ln_lilongwe <- ts(analysis_data$ln_lilongwe, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_ln_blantyre <- ts(analysis_data$ln_blantyre, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_ln_mwanza <- ts(analysis_data$ln_mwanza, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

#Transform generation data so it can be visualized with radiance data (/100)
analysis_data$generation_scaled <- analysis_data$Total_generation/100
#Transform generation data so it can be visualized with ln(radiance) (/10000)
analysis_data$generation_scaled2 <- (analysis_data$Total_generation/1000000)*2

ts_generation_scaled1 <- ts(analysis_data$generation_scaled, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))

ts_generation_scaled2 <- ts(analysis_data$generation_scaled2, frequency=12, start=c(2012, 05, 01), end=c(2018, 05, 01))


#Total generation (scaled) & radiance 
ggplot(analysis_data, aes(x=analysis_data[,1]))+
  geom_line(aes(y=analysis_data$generation_scaled2, color="Total Generation"))+
  geom_line(aes(y=analysis_data[,33], color="Total Radiance, log"))+
  xlab("Month, Year")+
  ylab("")+
  ggtitle("Hydropower generation and log radiance over time")+
  labs(color="")

#Total generation (scaled) & central region 
ggplot(analysis_data, aes(x=analysis_data[,1]))+
  geom_line(aes(y=analysis_data$generation_scaled2, color="Total Generation"))+
  geom_line(aes(y=analysis_data$ln_central, color="Central Region Radiance, log"))+
  xlab("Month, Year")+
  ylab("")+
  ggtitle("Hydropower generation and log radiance over time in Central Region")+
  labs(color="")


#scale log radiance for visualization
analysis_data$log_rad_scaled <- analysis_data$ln_radiance-9


ggplot(analysis_data, aes(x=analysis_data[,1]))+
  geom_line(aes(y=analysis_data[,2], color="Capacity Factor"))+
  geom_line(aes(y=analysis_data[,42], color="Total Radiance, log"))+
  xlab("Month, Year")+
  ylab("")+
  ggtitle("Hydropower capacity factor and log radiance over time")+
  labs(color="")


Total <- tslm(ts_lnradiance ~ ts_hydro_monthly)
summary(Total, robust=TRUE)

Central <- tslm(ts_ln_central ~ ts_hydro_monthly)
summary(Central, robust=TRUE)

Northern <- tslm(ts_ln_northern ~ ts_hydro_monthly)
summary(Northern, robust=TRUE)

Southern <- tslm(ts_ln_southern ~ ts_hydro_monthly)
summary(Southern, robust=TRUE)

Lilongwe <- tslm(ts_ln_lilongwe ~ ts_hydro_monthly)
summary(Lilongwe, robust=TRUE)

Blantyre <- tslm(ts_ln_blantyre ~ ts_hydro_monthly)
summary(Blantyre, robust=TRUE)

Mwanza <- tslm(ts_ln_mwanza ~ ts_hydro_monthly)
summary(Mwanza, robust=TRUE)

#Naive models
tab_model(Total, Central, Northern, Southern, Lilongwe, Blantyre, Mwanza,
          pred.labels = c("Intercept", "Total generation"),
          dv.labels = c("Total", "Central", "Northern", "Southern", "Lilongwe", "Blantyre", "Mwanza"),
          show.ci = FALSE,
          collapse.se = TRUE,
          show.fstat = TRUE)

#Models with trend & seasonality
Total2 <- tslm(ts_lnradiance ~ ts_hydro_monthly + trend + season)
Central2 <- tslm(ts_ln_central ~ ts_hydro_monthly + trend + season)
Northern2 <- tslm(ts_ln_northern ~ ts_hydro_monthly + trend + season)
Southern2 <- tslm(ts_ln_southern ~ ts_hydro_monthly + trend + season)
Lilongwe2 <- tslm(ts_ln_lilongwe ~ ts_hydro_monthly + trend + season)
Blantyre2 <- tslm(ts_ln_blantyre ~ ts_hydro_monthly + trend + season)
Mwanza2 <- tslm(ts_ln_mwanza ~ ts_hydro_monthly + trend + season)

tab_model(Total2, Central2, Northern2, Southern2, Lilongwe2, Blantyre2, Mwanza2,
          pred.labels = c("Intercept", "Total generation", "Trend", "June", "July", "August", "September", "October", "November", "December", "January", "February", "March", "April"),
          dv.labels = c("Total", "Central", "Northern", "Southern", "Lilongwe", "Blantyre", "Mwanza"),
          show.ci = FALSE,
          collapse.se = TRUE,
          show.fstat = TRUE)

summary(Mwanza, robust=TRUE)

```


